### ISSUE TITLE
Training Caffe models with Quantized-CNN

### ISSUE THREAD

**Issue by zencoding** [jiaxiang-wu/quantized-cnn#1]
Hi,
   Thanks for code reproducing the paper, I was able to reproduce the test phase computation following the directions.  I was however unable to find any code to generate compact representation (BIN) files for Caffe models, the AlexNet is provided in the repo but there is no code to create the BIN files for models such as VggCnnS or CaffeNet.  I reviewed the code, it is basically loading precomputed code files from BIN files and then performing optimized layer operations on it.

Do you have any instructions or code on how to use pretrained Caffe models and generate the corresponding BIN files?

**Comment by jiaxiang-wu** [comment]
The current repo does not contain any code to convert the pre-trained Caffe model to its compressed counterpart. It merely demonstrates how the test-phase computation can be accelerated.

If you need to adopt our method to other Caffe models (besides AlexNet), I suggest you to closely follow the instructions in the paper. You may want to start with the quantization of fully-connected layers, since it is easier to implement, and also gives some hints to the quantization of convolutional layers.

**Comment by jiaxiang-wu** [comment]
The current repo does not contain any code to convert the pre-trained Caffe model to its compressed counterpart. It merely demonstrates how the test-phase computation can be accelerated.

If you need to adopt our method to other Caffe models (besides AlexNet), I suggest you to closely follow the instructions in the paper. You may want to start with the quantization of fully-connected layers, since it is easier to implement, and also gives some hints to the quantization of convolutional layers.
