### ISSUE TITLE
Is QCNN suitable to fully convolution net(FCN)？

### ISSUE THREAD

**Issue by hiyijian** [jiaxiang-wu/quantized-cnn#6]
Dear @jiaxiang-wu ,
  I noitced that the input data size of all example nets are fixed.  What if test image size are diffrient from each other? For example, some pixel-wise classification tasks run on FCN.  Theoretically, Can the quantized technology apply on FCN?  If yes, any modification on this project needed? 
  Best regard

**Comment by jiaxiang-wu** [comment]
Dear @hiyijian ,

We fixed the input data size due to the existence of fully-connected layers. If fully-connected layers are removed, I think it is possible to remove such constraint on the constant input data size. Q-CNN is designed to approximate the input-output relationship of the original network, so it should works for FCN as well.
You may need to modify the memory pre-allocation part in src/CaffeEva.cc for feature maps, look-up tables, and other auxiliary variables.

Best,

**Comment by hiyijian** [comment]
Clear now. I readed this project yesterday and learned quite a lot from it. Much thanks.
